# Econ 390 - Lecture 19: Merging
Today we will go over how to merge datasets. We will be covering much of [8.1 and 8.2 from McKinney](https://wesmckinney.com/book/data-wrangling) and [Joins in Turrell](https://aeturrell.github.io/coding-for-economists/data-joining-data.html#joins).

In [1]:
import pandas as pd

econ390path = "https://m-mcmain.github.io/files/Econ390SP26/"

## Concatenate

In [2]:
# Read in the data
telework2023 = pd.read_csv(econ390path + "state-telework-2023.csv", index_col = 0)
telework2024 = pd.read_csv(econ390path + "state-telework-2024.csv", index_col = 0)

telework2023.head()

            Teleworked_Some  Teleworked_All  Year
State
Alabama                 3.0             4.6  2023
Alaska                  7.8             6.1  2023
Arizona                10.0            13.9  2023
Arkansas                3.9             5.1  2023
California             11.5            11.1  2023

In [3]:
# concat method
pd.concat([telework2023, telework2024], axis = 1)

,Teleworked_Some,Teleworked_All,Year,Teleworked_Some,Teleworked_All,Year
State,,,,,,
Alabama,3.0,4.6,2023.0,4.4,6.3,2024
Alaska,7.8,6.1,2023.0,9.5,7.2,2024
Arizona,10.0,13.9,2023.0,12.6,14.9,2024
Arkansas,3.9,5.1,2023.0,6.0,5.6,2024
California,11.5,11.1,2023.0,14.1,11.4,2024
Colorado,16.0,15.8,2023.0,16.6,15.7,2024
Connecticut,14.4,10.7,2023.0,16.2,9.0,2024
Delaware,10.5,10.0,2023.0,11.6,10.7,2024
District of Columbia,33.1,23.4,2023.0,36.0,20.8,2024
Florida,5.3,10.0,2023.0,7.7,11.3,2024
Georgia,6.9,10.9,2023.0,10.6,11.6,2024
Hawaii,6.5,6.4,2023.0,8.9,6.8,2024
Idaho,7.2,8.0,2023.0,9.1,10.6,2024
Illinois,11.2,9.7,2023.0,14.5,11.8,2024
Indiana,7.4,7.4,2023.0,10.3,7.9,2024
Iowa,5.6,6.6,2023.0,8.9,6.8,2024
Kansas,8.0,8.5,2023.0,11.3,9.0,2024
Kentucky,6.6,6.6,2023.0,8.1,7.5,2024
Louisiana,4.0,5.5,2023.0,6.5,6.3,2024
Maine,10.1,11.6,2023.0,11.9,11.6,2024
Maryland,13.0,14.6,2023.0,16.3,14.1,2024
Massachusetts,16.1,13.3,2023.0,18.9,12.6,2024
Michigan,10.2,10.3,2023.0,11.9,9.3,2024
Minnesota,12.7,12.4,2023.0,14.5,11.4,2024
Mississippi,1.6,3.1,2023.0,2.9,4.4,2024
Missouri,7.6,9.3,2023.0,11.7,10.0,2024
Montana,7.2,8.8,2023.0,10.6,10.0,2024
Nebraska,8.5,8.7,2023.0,9.6,8.7,2024
Nevada,5.1,7.9,2023.0,6.5,9.7,2024
New Hampshire,10.4,12.0,2023.0,12.8,13.2,2024
New Jersey,13.1,11.2,2023.0,15.9,11.2,2024
New Mexico,5.8,7.2,2023.0,8.5,8.9,2024
New York,10.7,8.6,2023.0,12.8,8.4,2024
North Carolina,8.2,10.4,2023.0,10.7,11.3,2024
North Dakota,5.3,6.0,2023.0,7.9,6.5,2024
Ohio,9.4,9.3,2023.0,11.4,9.9,2024
Oklahoma,5.7,5.3,2023.0,7.6,7.1,2024
Oregon,12.1,14.1,2023.0,14.1,15.3,2024
Pennsylvania,10.2,11.0,2023.0,12.3,11.5,2024
Rhode Island,9.4,9.9,2023.0,14.1,9.2,2024
South Carolina,5.8,8.3,2023.0,8.7,9.6,2024
South Dakota,4.0,5.5,2023.0,7.7,6.8,2024
Tennessee,6.8,8.5,2023.0,9.0,10.5,2024
Texas,7.7,10.7,2023.0,10.8,11.7,2024
Utah,9.8,12.0,2023.0,13.2,13.6,2024
Vermont,10.8,11.8,2023.0,14.0,12.3,2024
Virginia,13.3,13.9,2023.0,15.1,13.5,2024
Washington,14.0,14.5,2023.0,16.3,14.5,2024
West Virginia,4.2,5.2,2023.0,5.9,6.5,2024
Wisconsin,8.0,8.4,2023.0,11.8,10.1,2024
Wyoming,5.1,5.1,2023.0,6.4,7.1,2024
All States,NaN,NaN,NaN,11.9,10.9,2024

In [4]:
# Now specify the type for Year in the telework 2023 data
telework2023 = pd.read_csv(econ390path + "state-telework-2023.csv", dtype = {"Year":"Int64"}, index_col = 0)
telework2024 = pd.read_csv(econ390path + "state-telework-2024.csv", index_col = 0)

telework2023.head()

            Teleworked_Some  Teleworked_All  Year
State
Alabama                 3.0             4.6  2023
Alaska                  7.8             6.1  2023
Arizona                10.0            13.9  2023
Arkansas                3.9             5.1  2023
California             11.5            11.1  2023

In [5]:
# This is still Bad
pd.concat([telework2023, telework2024], axis = 0)

               Teleworked_Some  Teleworked_All  Year
State
Alabama                    3.0             4.6  2023
Alaska                     7.8             6.1  2023
Arizona                   10.0            13.9  2023
Arkansas                   3.9             5.1  2023
California                11.5            11.1  2023
...                        ...             ...   ...
Virginia                  15.1            13.5  2024
Washington                16.3            14.5  2024
West Virginia              5.9             6.5  2024
Wisconsin                 11.8            10.1  2024
Wyoming                    6.4             7.1  2024

[103 rows x 3 columns]

In [6]:
# Now we can have concat do even more work for us
Years = [2023, 2024]
pd.concat([telework2023, telework2024], keys = Years, axis = 0)

                    Teleworked_Some  Teleworked_All  Year
     State
2023 Alabama                    3.0             4.6  2023
     Alaska                     7.8             6.1  2023
     Arizona                   10.0            13.9  2023
     Arkansas                   3.9             5.1  2023
     California                11.5            11.1  2023
...                             ...             ...   ...
2024 Virginia                  15.1            13.5  2024
     Washington                16.3            14.5  2024
     West Virginia              5.9             6.5  2024
     Wisconsin                 11.8            10.1  2024
     Wyoming                    6.4             7.1  2024

[103 rows x 3 columns]

## Hierarchical Indexing

In [7]:
# Reset to just State as index
telework_stacked = pd.concat([telework2023, telework2024], axis = 0)
telework_stacked

               Teleworked_Some  Teleworked_All  Year
State
Alabama                    3.0             4.6  2023
Alaska                     7.8             6.1  2023
Arizona                   10.0            13.9  2023
Arkansas                   3.9             5.1  2023
California                11.5            11.1  2023
...                        ...             ...   ...
Virginia                  15.1            13.5  2024
Washington                16.3            14.5  2024
West Virginia              5.9             6.5  2024
Wisconsin                 11.8            10.1  2024
Wyoming                    6.4             7.1  2024

[103 rows x 3 columns]

In [8]:
# Set two indices?
telework_stacked.reset_index().set_index(["State", "Year"])

                    Teleworked_Some  Teleworked_All
State         Year
Alabama       2023              3.0             4.6
Alaska        2023              7.8             6.1
Arizona       2023             10.0            13.9
Arkansas      2023              3.9             5.1
California    2023             11.5            11.1
...                             ...             ...
Virginia      2024             15.1            13.5
Washington    2024             16.3            14.5
West Virginia 2024              5.9             6.5
Wisconsin     2024             11.8            10.1
Wyoming       2024              6.4             7.1

[103 rows x 2 columns]

In [9]:
# Change the order?
telework_stacked.reset_index().set_index(["Year","State"])

                    Teleworked_Some  Teleworked_All
Year State
2023 Alabama                    3.0             4.6
     Alaska                     7.8             6.1
     Arizona                   10.0            13.9
     Arkansas                   3.9             5.1
     California                11.5            11.1
...                             ...             ...
2024 Virginia                  15.1            13.5
     Washington                16.3            14.5
     West Virginia              5.9             6.5
     Wisconsin                 11.8            10.1
     Wyoming                    6.4             7.1

[103 rows x 2 columns]

In [10]:
# Setting the index with options
telework_stacked.set_index("Year", append=True, inplace = True)
telework_stacked

                    Teleworked_Some  Teleworked_All
State         Year
Alabama       2023              3.0             4.6
Alaska        2023              7.8             6.1
Arizona       2023             10.0            13.9
Arkansas      2023              3.9             5.1
California    2023             11.5            11.1
...                             ...             ...
Virginia      2024             15.1            13.5
Washington    2024             16.3            14.5
West Virginia 2024              5.9             6.5
Wisconsin     2024             11.8            10.1
Wyoming       2024              6.4             7.1

[103 rows x 2 columns]

In [11]:
# What *is* the index?
telework_stacked.index

MultiIndex([(             'Alabama', 2023),
            (              'Alaska', 2023),
            (             'Arizona', 2023),
            (            'Arkansas', 2023),
            (          'California', 2023),
            (            'Colorado', 2023),
            (         'Connecticut', 2023),
            (            'Delaware', 2023),
            ('District of Columbia', 2023),
            (             'Florida', 2023),
            ...
            (        'South Dakota', 2024),
            (           'Tennessee', 2024),
            (               'Texas', 2024),
            (                'Utah', 2024),
            (             'Vermont', 2024),
            (            'Virginia', 2024),
            (          'Washington', 2024),
            (       'West Virginia', 2024),
            (           'Wisconsin', 2024),
            (             'Wyoming', 2024)],
           names=['State', 'Year'], length=103)

In [12]:
# How does sort work
telework_stacked.sort_values('Teleworked_All')

                           Teleworked_Some  Teleworked_All
State                Year
Mississippi          2023              1.6             3.1
                     2024              2.9             4.4
Alabama              2023              3.0             4.6
Arkansas             2023              3.9             5.1
Wyoming              2023              5.1             5.1
...                                    ...             ...
Oregon               2024             14.1            15.3
Colorado             2024             16.6            15.7
                     2023             16.0            15.8
District of Columbia 2024             36.0            20.8
                     2023             33.1            23.4

[103 rows x 2 columns]

In [13]:
# Sort in descending order
telework_stacked.sort_values('Teleworked_All', ascending=False)

                           Teleworked_Some  Teleworked_All
State                Year
District of Columbia 2023             33.1            23.4
                     2024             36.0            20.8
Colorado             2023             16.0            15.8
                     2024             16.6            15.7
Oregon               2024             14.1            15.3
...                                    ...             ...
Arkansas             2023              3.9             5.1
Wyoming              2023              5.1             5.1
Alabama              2023              3.0             4.6
Mississippi          2024              2.9             4.4
                     2023              1.6             3.1

[103 rows x 2 columns]

In [14]:
# Sorting on index?
telework_stacked.sort_index

<bound method DataFrame.sort_index of                     Teleworked_Some  Teleworked_All
State         Year
Alabama       2023              3.0             4.6
Alaska        2023              7.8             6.1
Arizona       2023             10.0            13.9
Arkansas      2023              3.9             5.1
California    2023             11.5            11.1
...                             ...             ...
Virginia      2024             15.1            13.5
Washington    2024             16.3            14.5
West Virginia 2024              5.9             6.5
Wisconsin     2024             11.8            10.1
Wyoming       2024              6.4             7.1

[103 rows x 2 columns]>

In [15]:
# Specify different levels and ascending
telework_stacked.sort_index(level=['Year','State'], ascending=[True,False])

                    Teleworked_Some  Teleworked_All
State         Year
Wyoming       2023              5.1             5.1
Wisconsin     2023              8.0             8.4
West Virginia 2023              4.2             5.2
Washington    2023             14.0            14.5
Virginia      2023             13.3            13.9
...                             ...             ...
Arkansas      2024              6.0             5.6
Arizona       2024             12.6            14.9
All States    2024             11.9            10.9
Alaska        2024              9.5             7.2
Alabama       2024              4.4             6.3

[103 rows x 2 columns]

In [16]:
# Alternative options for sort_index
telework_stacked.sort_index(level=[0,1], ascending=[True,False])

                    Teleworked_Some  Teleworked_All
State         Year
Alabama       2024              4.4             6.3
              2023              3.0             4.6
Alaska        2024              9.5             7.2
              2023              7.8             6.1
All States    2024             11.9            10.9
...                             ...             ...
West Virginia 2023              4.2             5.2
Wisconsin     2024             11.8            10.1
              2023              8.0             8.4
Wyoming       2024              6.4             7.1
              2023              5.1             5.1

[103 rows x 2 columns]

In [17]:
# Basic
telework_stacked.sort_index(inplace=True)
telework_stacked

                    Teleworked_Some  Teleworked_All
State         Year
Alabama       2023              3.0             4.6
              2024              4.4             6.3
Alaska        2023              7.8             6.1
              2024              9.5             7.2
All States    2024             11.9            10.9
...                             ...             ...
West Virginia 2024              5.9             6.5
Wisconsin     2023              8.0             8.4
              2024             11.8            10.1
Wyoming       2023              5.1             5.1
              2024              6.4             7.1

[103 rows x 2 columns]

In [18]:
# Finding specific entries for one index
telework_stacked.loc["Wisconsin",:]

      Teleworked_Some  Teleworked_All
Year
2023              8.0             8.4
2024             11.8            10.1

In [19]:
# Finding specific entries for two indices
telework_stacked.loc[("Wisconsin", 2023),:]

Teleworked_Some    8.0
Teleworked_All     8.4
Name: (Wisconsin, 2023), dtype: float64

In [20]:
# Comparison
telework_stacked.loc["Wisconsin"]

      Teleworked_Some  Teleworked_All
Year
2023              8.0             8.4
2024             11.8            10.1

In [21]:
# Stacked Loc
telework_stacked.loc[("Wisconsin", 2023)]

Teleworked_Some    8.0
Teleworked_All     8.4
Name: (Wisconsin, 2023), dtype: float64

In [22]:
# xs turns the dataframe into a cross section for the specified index
telework_stacked.xs(2023, level="Year")

                      Teleworked_Some  Teleworked_All
State
Alabama                           3.0             4.6
Alaska                            7.8             6.1
Arizona                          10.0            13.9
Arkansas                          3.9             5.1
California                       11.5            11.1
Colorado                         16.0            15.8
Connecticut                      14.4            10.7
Delaware                         10.5            10.0
District of Columbia             33.1            23.4
Florida                           5.3            10.0
Georgia                           6.9            10.9
Hawaii                            6.5             6.4
Idaho                             7.2             8.0
Illinois                         11.2             9.7
Indiana                           7.4             7.4
Iowa                              5.6             6.6
Kansas                            8.0             8.5
Kentucky                          6.6             6.6
Louisiana                         4.0             5.5
Maine                            10.1            11.6
Maryland                         13.0            14.6
Massachusetts                    16.1            13.3
Michigan                         10.2            10.3
Minnesota                        12.7            12.4
Mississippi                       1.6             3.1
Missouri                          7.6             9.3
Montana                           7.2             8.8
Nebraska                          8.5             8.7
Nevada                            5.1             7.9
New Hampshire                    10.4            12.0
New Jersey                       13.1            11.2
New Mexico                        5.8             7.2
New York                         10.7             8.6
North Carolina                    8.2            10.4
North Dakota                      5.3             6.0
Ohio                              9.4             9.3
Oklahoma                          5.7             5.3
Oregon                           12.1            14.1
Pennsylvania                     10.2            11.0
Rhode Island                      9.4             9.9
South Carolina                    5.8             8.3
South Dakota                      4.0             5.5
Tennessee                         6.8             8.5
Texas                             7.7            10.7
Utah                              9.8            12.0
Vermont                          10.8            11.8
Virginia                         13.3            13.9
Washington                       14.0            14.5
West Virginia                     4.2             5.2
Wisconsin                         8.0             8.4
Wyoming                           5.1             5.1

In [23]:
# Different process, same result
telework_stacked.xs("Wisconsin", level="State")

      Teleworked_Some  Teleworked_All
Year
2023              8.0             8.4
2024             11.8            10.1

In [24]:
# Keep the level
telework_stacked.xs("Wisconsin", level="State", drop_level=False)

                Teleworked_Some  Teleworked_All
State     Year
Wisconsin 2023              8.0             8.4
          2024             11.8            10.1

In [25]:
# Multiple states?
telework_stacked.xs(["Wisconsin","Michigan"], level="State", drop_level=False)

TypeError: list keys are not supported in xs, pass a tuple instead

In [26]:
# Work around with concat
telework_WI = telework_stacked.xs("Wisconsin", level="State", drop_level=False)
telework_MI = telework_stacked.xs("Michigan", level="State", drop_level=False)
pd.concat([telework_WI, telework_MI])

                Teleworked_Some  Teleworked_All
State     Year
Wisconsin 2023              8.0             8.4
          2024             11.8            10.1
Michigan  2023             10.2            10.3
          2024             11.9             9.3

In [27]:
# Loc works fine
telework_stacked.loc[["Wisconsin", "Michigan"]]

                Teleworked_Some  Teleworked_All
State     Year
Wisconsin 2023              8.0             8.4
          2024             11.8            10.1
Michigan  2023             10.2            10.3
          2024             11.9             9.3

In [28]:
# send to csv
telework_stacked.to_csv("telework_stacked.csv")

In [29]:
# read in with multiple indices
pd.read_csv("telework_stacked.csv", index_col = ["State", "Year"])

                    Teleworked_Some  Teleworked_All
State         Year
Alabama       2023              3.0             4.6
              2024              4.4             6.3
Alaska        2023              7.8             6.1
              2024              9.5             7.2
All States    2024             11.9            10.9
...                             ...             ...
West Virginia 2024              5.9             6.5
Wisconsin     2023              8.0             8.4
              2024             11.8            10.1
Wyoming       2023              5.1             5.1
              2024              6.4             7.1

[103 rows x 2 columns]

## Practice - Hierarchical Indexing
1. Find the telework data for D.C.
2. Find the telework data for D.C. in 2023
3. Find the percent of workers who entirely teleworked in D.C. in 2023
4. Get all of the data for teleworking in 2023

In [30]:
# Results
print(telework_stacked.loc["District of Columbia"])
print(telework_stacked.loc["District of Columbia", 2023])
print(telework_stacked.loc["District of Columbia", 2023].loc["Teleworked_All"])
telework_stacked.xs(2023, level="Year")

      Teleworked_Some  Teleworked_All
Year
2023             33.1            23.4
2024             36.0            20.8
Teleworked_Some    33.1
Teleworked_All     23.4
Name: (District of Columbia, 2023), dtype: float64
23.4

                      Teleworked_Some  Teleworked_All
State
Alabama                           3.0             4.6
Alaska                            7.8             6.1
Arizona                          10.0            13.9
Arkansas                          3.9             5.1
California                       11.5            11.1
Colorado                         16.0            15.8
Connecticut                      14.4            10.7
Delaware                         10.5            10.0
District of Columbia             33.1            23.4
Florida                           5.3            10.0
Georgia                           6.9            10.9
Hawaii                            6.5             6.4
Idaho                             7.2             8.0
Illinois                         11.2             9.7
Indiana                           7.4             7.4
Iowa                              5.6             6.6
Kansas                            8.0             8.5
Kentucky                          6.6             6.6
Louisiana                         4.0             5.5
Maine                            10.1            11.6
Maryland                         13.0            14.6
Massachusetts                    16.1            13.3
Michigan                         10.2            10.3
Minnesota                        12.7            12.4
Mississippi                       1.6             3.1
Missouri                          7.6             9.3
Montana                           7.2             8.8
Nebraska                          8.5             8.7
Nevada                            5.1             7.9
New Hampshire                    10.4            12.0
New Jersey                       13.1            11.2
New Mexico                        5.8             7.2
New York                         10.7             8.6
North Carolina                    8.2            10.4
North Dakota                      5.3             6.0
Ohio                              9.4             9.3
Oklahoma                          5.7             5.3
Oregon                           12.1            14.1
Pennsylvania                     10.2            11.0
Rhode Island                      9.4             9.9
South Carolina                    5.8             8.3
South Dakota                      4.0             5.5
Tennessee                         6.8             8.5
Texas                             7.7            10.7
Utah                              9.8            12.0
Vermont                          10.8            11.8
Virginia                         13.3            13.9
Washington                       14.0            14.5
West Virginia                     4.2             5.2
Wisconsin                         8.0             8.4
Wyoming                           5.1             5.1

## Merging

In [31]:
pd.merge(telework2023, telework2024)

Empty DataFrame
Columns: [Teleworked_Some, Teleworked_All, Year]
Index: []

In [32]:
pd.merge(telework2023, telework2024, on = "State")

,Teleworked_Some_x,Teleworked_All_x,Year_x,Teleworked_Some_y,Teleworked_All_y,Year_y
State,,,,,,
Alabama,3.0,4.6,2023,4.4,6.3,2024
Alaska,7.8,6.1,2023,9.5,7.2,2024
Arizona,10.0,13.9,2023,12.6,14.9,2024
Arkansas,3.9,5.1,2023,6.0,5.6,2024
California,11.5,11.1,2023,14.1,11.4,2024
Colorado,16.0,15.8,2023,16.6,15.7,2024
Connecticut,14.4,10.7,2023,16.2,9.0,2024
Delaware,10.5,10.0,2023,11.6,10.7,2024
District of Columbia,33.1,23.4,2023,36.0,20.8,2024
Florida,5.3,10.0,2023,7.7,11.3,2024
Georgia,6.9,10.9,2023,10.6,11.6,2024
Hawaii,6.5,6.4,2023,8.9,6.8,2024
Idaho,7.2,8.0,2023,9.1,10.6,2024
Illinois,11.2,9.7,2023,14.5,11.8,2024
Indiana,7.4,7.4,2023,10.3,7.9,2024
Iowa,5.6,6.6,2023,8.9,6.8,2024
Kansas,8.0,8.5,2023,11.3,9.0,2024
Kentucky,6.6,6.6,2023,8.1,7.5,2024
Louisiana,4.0,5.5,2023,6.5,6.3,2024
Maine,10.1,11.6,2023,11.9,11.6,2024
Maryland,13.0,14.6,2023,16.3,14.1,2024
Massachusetts,16.1,13.3,2023,18.9,12.6,2024
Michigan,10.2,10.3,2023,11.9,9.3,2024
Minnesota,12.7,12.4,2023,14.5,11.4,2024
Mississippi,1.6,3.1,2023,2.9,4.4,2024
Missouri,7.6,9.3,2023,11.7,10.0,2024
Montana,7.2,8.8,2023,10.6,10.0,2024
Nebraska,8.5,8.7,2023,9.6,8.7,2024
Nevada,5.1,7.9,2023,6.5,9.7,2024
New Hampshire,10.4,12.0,2023,12.8,13.2,2024
New Jersey,13.1,11.2,2023,15.9,11.2,2024
New Mexico,5.8,7.2,2023,8.5,8.9,2024
New York,10.7,8.6,2023,12.8,8.4,2024
North Carolina,8.2,10.4,2023,10.7,11.3,2024
North Dakota,5.3,6.0,2023,7.9,6.5,2024
Ohio,9.4,9.3,2023,11.4,9.9,2024
Oklahoma,5.7,5.3,2023,7.6,7.1,2024
Oregon,12.1,14.1,2023,14.1,15.3,2024
Pennsylvania,10.2,11.0,2023,12.3,11.5,2024
Rhode Island,9.4,9.9,2023,14.1,9.2,2024
South Carolina,5.8,8.3,2023,8.7,9.6,2024
South Dakota,4.0,5.5,2023,7.7,6.8,2024
Tennessee,6.8,8.5,2023,9.0,10.5,2024
Texas,7.7,10.7,2023,10.8,11.7,2024
Utah,9.8,12.0,2023,13.2,13.6,2024
Vermont,10.8,11.8,2023,14.0,12.3,2024
Virginia,13.3,13.9,2023,15.1,13.5,2024
Washington,14.0,14.5,2023,16.3,14.5,2024
West Virginia,4.2,5.2,2023,5.9,6.5,2024
Wisconsin,8.0,8.4,2023,11.8,10.1,2024
Wyoming,5.1,5.1,2023,6.4,7.1,2024

In [33]:
pd.merge(telework2023, telework2024, on = "State", suffixes = ("_23","_24")).drop(["Year_23", "Year_24"],axis=1)

,Teleworked_Some_23,Teleworked_All_23,Teleworked_Some_24,Teleworked_All_24
State,,,,
Alabama,3.0,4.6,4.4,6.3
Alaska,7.8,6.1,9.5,7.2
Arizona,10.0,13.9,12.6,14.9
Arkansas,3.9,5.1,6.0,5.6
California,11.5,11.1,14.1,11.4
Colorado,16.0,15.8,16.6,15.7
Connecticut,14.4,10.7,16.2,9.0
Delaware,10.5,10.0,11.6,10.7
District of Columbia,33.1,23.4,36.0,20.8
Florida,5.3,10.0,7.7,11.3
Georgia,6.9,10.9,10.6,11.6
Hawaii,6.5,6.4,8.9,6.8
Idaho,7.2,8.0,9.1,10.6
Illinois,11.2,9.7,14.5,11.8
Indiana,7.4,7.4,10.3,7.9
Iowa,5.6,6.6,8.9,6.8
Kansas,8.0,8.5,11.3,9.0
Kentucky,6.6,6.6,8.1,7.5
Louisiana,4.0,5.5,6.5,6.3
Maine,10.1,11.6,11.9,11.6
Maryland,13.0,14.6,16.3,14.1
Massachusetts,16.1,13.3,18.9,12.6
Michigan,10.2,10.3,11.9,9.3
Minnesota,12.7,12.4,14.5,11.4
Mississippi,1.6,3.1,2.9,4.4
Missouri,7.6,9.3,11.7,10.0
Montana,7.2,8.8,10.6,10.0
Nebraska,8.5,8.7,9.6,8.7
Nevada,5.1,7.9,6.5,9.7
New Hampshire,10.4,12.0,12.8,13.2
New Jersey,13.1,11.2,15.9,11.2
New Mexico,5.8,7.2,8.5,8.9
New York,10.7,8.6,12.8,8.4
North Carolina,8.2,10.4,10.7,11.3
North Dakota,5.3,6.0,7.9,6.5
Ohio,9.4,9.3,11.4,9.9
Oklahoma,5.7,5.3,7.6,7.1
Oregon,12.1,14.1,14.1,15.3
Pennsylvania,10.2,11.0,12.3,11.5
Rhode Island,9.4,9.9,14.1,9.2
South Carolina,5.8,8.3,8.7,9.6
South Dakota,4.0,5.5,7.7,6.8
Tennessee,6.8,8.5,9.0,10.5
Texas,7.7,10.7,10.8,11.7
Utah,9.8,12.0,13.2,13.6
Vermont,10.8,11.8,14.0,12.3
Virginia,13.3,13.9,15.1,13.5
Washington,14.0,14.5,16.3,14.5
West Virginia,4.2,5.2,5.9,6.5
Wisconsin,8.0,8.4,11.8,10.1
Wyoming,5.1,5.1,6.4,7.1